# Generated by Django 5.1.6 on 2025-03-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0017_remove_member_membership_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_Email',
            new_name='member_email',
        ),
        migrations.AddField(
            model_name='book',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='borrowed_books', to='lms_app.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='members', to='lms_app.book'),
        ),
    ]
