# Generated by Django 5.1.6 on 2025-03-06 18:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0019_book_due_date_book_fine_amount_book_status_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='fine_amount',
            new_name='book_price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='status_payment',
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status_payment', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=50)),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
