# Generated by Django 5.1.6 on 2025-03-06 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0020_rename_fine_amount_book_book_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_price',
        ),
    ]
