# Generated by Django 5.1.6 on 2025-03-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0021_remove_book_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
