# Generated by Django 5.1.6 on 2025-03-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0022_alter_billing_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
